### ISSUE TITLE
Write a design QA checklist

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#1]
Based on work done in this implementation ticket https://github.com/mozilla/internet-health-report/issues/31 We will be able to start QA very soon. 

Starting a check list in [this doc](https://docs.google.com/a/mozilla.com/document/d/1OTudHRgd1xR2uvlM5iVv-CyuzZbheIMrQmCSStJxtmQ/edit?usp=sharing). Once it's finalized, I will put list into a ticket.

**Comment by kristinashu** [comment]
@hannahkane would love to get your feedback on this!

**Comment by hannahkane** [comment]
List seems super thorough. This could be a great template for other projects! The only big category of things I can think of that might be missing is a section specifically on localization.

**Comment by kristinashu** [comment]
Excellent! 

I've put this into a ticket to start checking off https://github.com/mozilla/ihr-landing-site/issues/6 and opened a ticket in the design repo to make a more generic checklist https://github.com/MozillaFoundation/Design/issues/236
