### ISSUE TITLE
Bug: category tags show twice in some blogposts

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#10]
When I go on "Blog" and look at the blogpost, in two of them the category is displayed twice:

In "Digital Citizens, Let’s Talk About Internet Health", I see the category  "Research" twice
In "How would you measure the health of the Internet?", I see the category "Project Updates" twice

They are both correctly tagged with just one category in the backend and no other blogposts have this problem.

![screen shot 2017-07-31 at 2 32 35 pm](https://user-images.githubusercontent.com/22129061/28778142-5c726b4a-75fe-11e7-9293-0f1c9146881f.png)

@cadecairos @kristinashu can you have a look at this? thanks for your help!

**Comment by kristinashu** [comment]
@mzanni is looking into this but might need some files for Cade.

**Comment by kristinashu** [comment]
Mike and Cade have fixed this!

@kaodro, I had to re-re-name "Uncategorized" to "Project Updates" but don't know the translation for it. Can you please add the translations? E.g. https://healthreport.staging.wpengine.com/es/blog/

**Comment by kaodro** [comment]
Thanks for fixing! I updated the categories with google translate translations and will update it later once the translators are ready.
