### ISSUE TITLE
Bug: "Most recent" category doesn't separate languages and displays posts in all languages

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#11]
When I go to the "Blog" in the English version, the default "Most recent" category displays blogposts in Spanish as these were the ones most recently added. 
It seems that the category doesn't differentiate between languages and displays all posts, not only English ones. The "most recent" category should display posts according the the language set.

Strangely, the problem disappears when I go on a different category (Eg. "Deep Dive") and then back to "Most Recent". 
![screen shot 2017-07-31 at 2 41 38 pm](https://user-images.githubusercontent.com/22129061/28778077-0499cb98-75fe-11e7-89d7-5050906d738b.png)

@cadecairos @kristinashu

**Comment by kristinashu** [comment]
@mzanni thinks he has fixed this one. @kaodro you will be able to see the update once Cade has the chance to update the staging site.

**Comment by kristinashu** [comment]
Thanks, looks like this has been fixed!
