### ISSUE TITLE
Remove featured box from About page

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#12]
When I go on the About page and scroll down, at the bottom I see a featured post "archive of reports" that shouldn't be visible. I wasn't able to find a way to hide it in the backend, could you help? Thanks! 
@kristinashu 
CC @cadecairos 

Thanks!

**Comment by kristinashu** [comment]
I deleted the archived report post from that page so the section is now hidden (but will appear again if you and content to it).

https://healthreport.staging.wpengine.com/about/
