### ISSUE TITLE
Modify the page template to hide title

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#14]
On the "Feedback" page the title of the page, the word "feedback" (or in Spanish version "Comentarios") shows up above the iframe embed. Can we remove it from there? 
The title of the page in backend syncs with the menu item so I can't remove it from there.

I shortly talked to cade about it and he can't help as his expertise isn't wordpress, @kristinashu can you help? Or Mike?
Thank you!

![screen shot 2017-08-04 at 5 05 18 pm](https://user-images.githubusercontent.com/22129061/28976271-8398cf1a-793d-11e7-8c90-310cd5f04129.png)
![screen shot 2017-08-04 at 5 53 45 pm](https://user-images.githubusercontent.com/22129061/28976270-839819b2-793d-11e7-833f-bdea6d147a17.png)

**Comment by mzanni** [comment]
I've added a new template to select for the pages called 'No Title Template'

**Comment by kristinashu** [comment]
Prefect! The title is now hidden.
