### ISSUE TITLE
Navigation links in translated pages lead back to English version

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#15]
When I click on "Lee mas" (read more) in the Spanish page (https://healthreport.staging.wpengine.com/es/) I end up in the English About page instead of the Spanish one. The same happens when I go on "View all blogposts" on the Spanish page - I end up in the English page.

Thanks for solving!

@kristinashu

**Comment by kristinashu** [comment]
Mike is looking into this!

**Comment by mzanni** [comment]
I had added a fix for this a while ago. I'm hoping it works and that Chris just didn't get my last update.
it will be included with my files for some other translation bug fixes I'll send him shortly

**Comment by kristinashu** [comment]
Thanks! This is now working on production.
