### ISSUE TITLE
Can't find various strings for translation in "Strings translation"

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#16]
I have a weird small problem with the translations; I've been translating the strings via the plugin via "Strings translation" -> basically searching for each string of the UI I found on the website and so far I was able to find all of them except for one: "related posts". I tried direct search and related search terms and went to source code of the website with the hope to find the identifier but nothing worked. I was able to find "featured blog posts" without much problem (a similar type of string) but "related posts" is nowhere to be found.

Is there another way to check where this string is hiding?
This is time critical cause as you know we want to be ready to push to production tomorrow.

Thanks in advance!

@kristinashu @cadecairos

**Comment by kaodro** [comment]
I also can't find "comments" right under the blogpost title. I found several other "comments" but not this. 
![screen shot 2017-08-08 at 10 31 25 pm](https://user-images.githubusercontent.com/22129061/29093133-09b5a818-7c89-11e7-8271-3a9df6ee3927.png)

Also can't find "Leave a reply".
![screen shot 2017-08-08 at 10 36 52 pm](https://user-images.githubusercontent.com/22129061/29093323-bd9d4a5c-7c89-11e7-9bdc-5dcda1784b42.png)

Also missing:

error messages for Sign-up:
"We are sorry, but there was a problem with our system. Please try again later!"
"Please check this box if you want to proceed."

"Sorry, no results were found" - I found two of these, changes both but none of it showed up as the translation on the website after search with no results. 

![screen shot 2017-08-09 at 3 41 35 pm](https://user-images.githubusercontent.com/22129061/29124301-da3d2918-7d18-11e7-858e-00f5997959bb.png)

**Comment by mzanni** [comment]
I can't find a way to translate the 'leave a reply'
it seems to be an issue with wpdiscuz not creating it as a translatable field, kind of a plugin limitation. it also says it's not wpml compatible. I think I'd have to edit the plugin to fix it and then my changes would be gone if it ever gets upgraded. thoughts?

these two errors are messages from the browser: if you have a localized version of FF you should see them in the proper language:
"We are sorry, but there was a problem with our system. Please try again later!"
"Please check this box if you want to proceed."

the comments, 1 comment, and  # comments should be translatable once Chris adds the new files I'm giving him

**Comment by mzanni** [comment]
the search had to be fixed to return the proper language for everything including the error message, and also added the 'related posts' as a translatable string

**Comment by kristinashu** [comment]
I don't think we should alter the wpdiscuz plugin since if might cause more problems than it will solve. @kaodro are you ok to have 'leave a reply' in English?

Thanks for all those other fixes Mike!

**Comment by kaodro** [comment]
@mzanni thanks so much! And yes, we are ok with having "leave a reply" in English, no problem.
/cc @kristinashu

**Comment by kristinashu** [comment]
@kaodro these updates are now live so you should be able to go in and translate "comments" and "leave a reply".

Once you have done that then we can close this ticket.

**Comment by kaodro** [comment]
Great, worked. I translated comments, 1 comment, #comments and "related posts" and the search works now, too. Awesome!
