### ISSUE TITLE
Hypothesis plugin isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#17]
Clicking on "annotate" at the top of the blog post or highlighting a sentence can clicking "annoate" should open the side bar but it isn't doing anything right now (e.g. https://healthreport.staging.wpengine.com/2017/01/19/digital-citizens-lets-talk-about-internet-health/).

This used to work but doesn't anymore.

@cadecairos is this something you are able to fix or will Mike need to do it?

cc @kaodro

**Comment by cadecairos** [comment]
This is a Content Security Policy issue - I will have to audit the site to whitelist various URLs and resources in our policy

**Comment by cadecairos** [comment]
OK I think I've got everything that we load listed in the Content Security Policy now.

**Comment by kristinashu** [comment]
Excellent, thank you!
