### ISSUE TITLE
Sign-up form shows error (sometimes)

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#19]
When I try to sign-up for updates I get an error, in all languages.  
![screen shot 2017-08-09 at 1 33 36 pm](https://user-images.githubusercontent.com/22129061/29119771-bc1ef346-7d07-11e7-8bd6-040edd3b8099.png)

Then it works for a moment and then it doesn't work again. If I try to subscribe to another language with the same email address, I don't get a confirmation email (not so critical cause probably nb will do it but maybe worth looking into it).
@cadecairos are you able to look into this? thank you!

**Comment by cadecairos** [comment]
This worked fine for me in all languages. If you're continually submitting the same email address, maybe the email signup endpoint is rejecting it due to rate limiting?

**Comment by kaodro** [comment]
OK, if you tested it recently then I guess it has to be it. Is there a way to verify it again without submitting the same emails (I only have 3, all used)

**Comment by cadecairos** [comment]
if you use `example.com` email addresses, the newsletter signup will know you're just testing that form submissions are working, and it should not rate limit you.

If that doesn't fix it, you might be seeing an error caused by a security/privacy plugin.

**Comment by kaodro** [comment]
It worked with the example.com email, I got the right message. I assume the emails get send correctly, too. Thanks!

**Comment by kristinashu** [comment]
@vojtechmzl should be able to confirm that it is all working?

**Comment by vojtechsedlak** [comment]
Yup, everything seems to be working fine in terms of data flow. The only tweak that would be great to add is a Google Analytics event that gets triggered when someone submits the form, so that we can measure conversions on the site. Let me know if I can help with that in any way. Thanks!

**Comment by kristinashu** [comment]
Thanks @vojtechmzl! How can we add the analytic event? Do you provide the script and then an engineer adds it in?

**Comment by vojtechsedlak** [comment]
Below is the code that should be triggered with the form submission. 

It can either be added to the signup button:

`onclick="ga('send', 'event', 'Signup', 'Form Submitted', 'Internet Health Report')"`

Or it can be added to the javascript:

`$('#newsletter_submit).onClick = ga('send', 'event', 'Signup', 'Form Submitted', 'Internet Health Report');`

**Comment by kristinashu** [comment]
Mike has added this script in and it's now of production.
