### ISSUE TITLE
Redirect old feedback page link to new website

### ISSUE THREAD

**Issue by Solanasaurus** [mozilla/ihr-landing-site#21]
We removed the feedback page on v.01 so there would only be one feedback page on the main website. However, we forgot that external links to the old page https://internethealthreport.org/v01/your-feedback/ will need to be redirected to https://internethealthreport.org/feedback/

@cadecairos is that something you can help with?
Cc: @mzanni @kristinashu @kaodro

**Comment by cadecairos** [comment]
We can add this redirect in WPEngine

**Comment by cadecairos** [comment]
Redirect is now in place: https://internethealthreport.org/v01/your-feedback/

```bash
> curl -i https://internethealthreport.org/v01/your-feedback/
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Fri, 11 Aug 2017 13:52:52 GMT
Content-Type: text/html
Content-Length: 178
Location: https://internethealthreport.org/feedback
Connection: keep-alive
Keep-Alive: timeout=20
```
