### ISSUE TITLE
Create graphics for IHR Call for Ideas

### ISSUE THREAD

**Issue by kaodro** [mozilla/ihr-landing-site#25]
Hi @beccaklam 
as discussed today we need graphics in the IHR aesthetics, with no text (they need to work in 4 languages) but something different from the standard emoji picture.

Details and copy for Call for Ideas: https://docs.google.com/document/d/1ZoljPpExR0n-IhX4UNut2-8S8qcEFk5_4UkELdAqveY/edit#

Graphics we need:
Banner for the website: 900x 506
Square graphic for instagram:  1080 x 1080
Banner graphic for Twitter: Minimum 440 x 220 (2:1 Ratio) 
Banner graphic for Facebook: 1200 x 630 pixels for the best display on high resolution devices. Callout box Emailing: https://drive.google.com/file/d/0Bzf0O6d7z8GGTDg1NENvU3JGUG8/view

Source for sizes: https://sproutsocial.com/insights/social-media-image-sizes-guide/ 

All this ideally by August 10.

Thank you!

**Comment by beccaklam** [comment]
Hi @kaodro, here's what I'm thinking so far for this graphic:
![artboard 1](https://user-images.githubusercontent.com/20977376/43875409-5193150e-9b5e-11e8-9da3-8c76b15d9d98.jpg)
It's still a work in progress but let me know if you have any feedback. Thanks!

**Comment by kaodro** [comment]
hey @beccaklam both me and Solana like it, great direction!

**Comment by kaodro** [comment]
@beccaklam we discussed this a little bit more and we would love to also have one version with a dinosaur or a cat or something fun. E.g. you could just paste a dinosaur on top of this beautiful background with a speech bubble saying "Internet Health Report Call for Ideas". In this case we would translate it so I would send you the translation to create 4 files. 

E.g. here is a dinosaurs we typically use: https://pbs.twimg.com/media/DioFVFjXkAACVm3.jpg:large

**Comment by beccaklam** [comment]
@kaodro Haha ok I'll see what I can do!

**Comment by beccaklam** [comment]
Hi @kaodro here is a redpen with both versions of the design (with the dino and without): https://redpen.io/p/gka6009d0942feb584 Let me know your thoughts/feedback. I can get you the final files tomorrow morning.

**Comment by Solanasaurus** [comment]
hi @beccaklam Kasia is offline today, but I think the dino is great. Thanks so much. Very classy touch with the black and white! Could you please change the text so it says "Submit your ideas for the next Internet Health Report". And also please give us some versions with speech bubbles but without text so we can add variations of text ourselves in different languages.

This background is perfect for putting different animals and speech bubbles. It's super helpful to have the different sizes for all the platforms!

I made a version with a cat too (here is the original cat https://unsplash.com/photos/zBvVuRJ71vU )

![cat asking questions](https://user-images.githubusercontent.com/22150791/43948953-88118820-9c8c-11e8-82cf-0e19c9079c4e.png)

Here is a different cat. Original link https://unsplash.com/photos/ZEd44nDPTfA

![cat asking questions 2](https://user-images.githubusercontent.com/22150791/43949949-4e59cd7e-9c8f-11e8-9ce6-c57c5681da22.png)

Here is a different dinosaur (original dino https://unsplash.com/photos/0poUUXA4C7w) 

![dinosaur asking questions](https://user-images.githubusercontent.com/22150791/43950394-7a8cefba-9c90-11e8-939c-790db35ba1b8.png)

I put everythign here so we can have everything in one place. If you have any ideas for improvements please go ahead, I just whipped these up in Preview app for fun. It seems cute/funny to have the animals speaking themselves in the first person.

**Comment by beccaklam** [comment]
Thanks @Solanasaurus! Those are so great :) I incorporated some of them into the design. Here is the zip file with all the final graphics: 
[ihr-call-for-ideas-graphics.zip](https://github.com/mozilla/ihr-landing-site/files/2278588/ihr-call-for-ideas-graphics.zip) Feel free to use whatever design works best for your purposes!
Here are some examples:
![facebook-cat](https://user-images.githubusercontent.com/20977376/43968093-21c1aa48-9c94-11e8-8b4f-cba384d16587.jpg)
![facebook-dino-2](https://user-images.githubusercontent.com/20977376/43968120-34b927f2-9c94-11e8-923f-9cc8d95b73d0.jpg)
![facebook-dino](https://user-images.githubusercontent.com/20977376/43968123-36eaeb14-9c94-11e8-895f-ae41d5dd8a0b.jpg)
![facebook](https://user-images.githubusercontent.com/20977376/43968126-39e6c9a0-9c94-11e8-83cb-242a37c187f7.jpg)
cc: @kaodro @xmatthewx

**Comment by kaodro** [comment]
Awesomeness!!!

**Comment by xmatthewx** [comment]
😯 🤣 🤪

**Comment by kaodro** [comment]
@beccaklam these are great, already using it for promo:) The only thing we miss now is the Callout box Emailing: https://drive.google.com/file/d/0Bzf0O6d7z8GGTDg1NENvU3JGUG8/view
For this one we would take a clean one (just background) and one with dinos head (to try how it looks:). Thanks!

**Comment by beccaklam** [comment]
Hi @kaodro so I'm pretty sure the email box size is 200x200 so I exported at 400x400 for higher res screens. Let me know if you need anything else or if Will says he needs a different format:
![email-bg](https://user-images.githubusercontent.com/20977376/44217697-12cce280-a146-11e8-986c-5a08beca1205.jpg)
![email-dino-2](https://user-images.githubusercontent.com/20977376/44217698-12cce280-a146-11e8-99b5-e164f1d12efa.jpg)
![email-dino-1](https://user-images.githubusercontent.com/20977376/44217699-12cce280-a146-11e8-999b-2c668010137e.jpg)

**Comment by beccaklam** [comment]
Hi @kaodro, so I'm pretty sure the dimensions for the email graphic are 200x200 so I exported at 2x for higher res screens. Let me know if Will needs something different. I also did both dinos since I didn't know which dino you wanted :)
![email-bg 2x](https://user-images.githubusercontent.com/20977376/44218163-1a40bb80-a147-11e8-86a9-e09f1093a41c.jpg)
![email-dino-2 2x](https://user-images.githubusercontent.com/20977376/44218164-1a40bb80-a147-11e8-9e56-128dcd4c038b.jpg)
![email-dino-1 2x](https://user-images.githubusercontent.com/20977376/44218165-1a40bb80-a147-11e8-861d-99f8d96f7085.jpg)

**Comment by beccaklam** [comment]
Going to close this ticket for now, reopen if needed!
