### ISSUE TITLE
Design updates to site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#5]
### Update image:
- [x] Update teaser image on the homepage for the Report v0.1 into something matching the colors of the report

**Comment by kristinashu** [comment]
@kaodro is this what you have in mind?
![images](https://user-images.githubusercontent.com/1068783/28891243-b4ed0baa-777e-11e7-80e7-600151f5609e.jpg)

It would look like this on the site (definitely more alarming and not as nice as the graph image):
![home 2x](https://user-images.githubusercontent.com/1068783/28891242-b4eb2f92-777e-11e7-8bf4-6516bf5ccad7.jpg)

**Comment by kaodro** [comment]
@kristinashu yes, nice! approved:) I added it to the site but feel free to exchange it with a better quality image.
