### ISSUE TITLE
Legal review of site

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#8]
I shared the site with legal expert Abigail and here is her initial feedback:

- At the bottom of the feedback form on the [Feedback page](https://healthreport.staging.wpengine.com/feedback/), could you replace the links above the "submit" button with: "Your responses are subject to the [Mozilla ToS](https://www.mozilla.org/en-US/about/legal/terms/mozilla/), [Privacy Policy](https://www.mozilla.org/en-US/privacy/websites/) and [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/)."

- Do we have permission to post all the photos in [this post](https://healthreport.staging.wpengine.com/2017/05/02/step-into-the-internet-health-clinic-republica-17/)?

@kaodro or @Solanasaurus are you able to update the Coral Feedback from with those links?

**Comment by kaodro** [comment]
@kristinashu 
Solana is on holiday until end of August and I don't have the login to the backend of the feedback form yet. She has it though so we will change it as soon as she is back and before we officially launch (will update it here once we do). As for the permissions: yes, we do have them. These are the pictures that all the speakers uploaded directly to their re:publica profiles. Cathleen Berger sent them an email before with their bios, letting them know that we would publicize this.

**Comment by kristinashu** [comment]
Sounds good, there's no big rush for this to get done.

**Comment by kaodro** [comment]
Legal notice updated.

**Comment by kristinashu** [comment]
Excellent, thanks @kaodro!

@cadecairos Abigail is also wondering if the [iFrame for the Coral Feedback form](https://healthreport.staging.wpengine.com/feedback/) is hosted on a Mozilla server. Do you know?

She also wants to know if https://web.hypothes.is/ used on the [Blog pages](https://healthreport.staging.wpengine.com/2017/05/02/step-into-the-internet-health-clinic-republica-17/) has gone through a security review?

**Comment by cadecairos** [comment]
I don't know much about how this form was first set up, but I think it's from an AWS S3 bucket owned by the Coral project folks.

I don't recall being asked for a risk review of hypothesis - I also don't see an open risk record for it.

**Comment by Solanasaurus** [comment]
I concur with Chris. I don’t think there was a formal security review for either service, perhaps because there wasn’t a “vendor” agreement for either. Sam and I didn’t know the risk/security review existed last year!

**Comment by kristinashu** [comment]
@cadecairos I've opened a ticket in bugzilla for a security review of Hypothesis. Could you please add any info you think might be helpful https://bugzilla.mozilla.org/show_bug.cgi?id=1390250 ? I've never filed one of these before.

@Solanasaurus Abigail said "I'd like to understand how IHR went about obtaining the bio pics permissions. We're (slowly) starting a project to get some kind of consistency around how permissions are requested, and I'm gathering data about how different teams handle." Do you mind if I loop you into the email so you can elaborate?

**Comment by kaodro** [comment]
@kristinashu if that is of any help, I posted Cathleen's response on how they got the permission in one of the above comments (pict uploaded to rp, Cathleen emailed them). But maybe Solana has sth to add to it.

**Comment by kristinashu** [comment]
I did pass that info on Abigail but she is still curious. Solana, if you have anything to add then let me know but otherwise I can just ask Abigail to follow up with Cathleen directly for more info. I think she is just gathering info to improve Mozilla's general process.

**Comment by Solanasaurus** [comment]
Hi @kristinashu Do you mean the photos in the articles? We just asked people for each of them and under what license they were willing to share. It’s not the same for all. Got a couple of permissions from flickr too. Happy to explain.

Also: I don’t have access to the Hypothes.is security bug but the developer I have been in touch with (and knows about our project) is named Rob Knight robertknight@hypothes.is + product manager Arti Walker artijwalker@hypothes.is. Those are probably the best people on their team to reach out to.

Best,
Solana

**Comment by kristinashu** [comment]
Thanks Solana, I'll cc you in the email but hopefully that is enough info.

Mozilla's security team have said that a security review is not necessary so hopefully legal is ok with that too!

**Comment by kristinashu** [comment]
Yay! We're all good!
